config/routes.rb
Hw5app::Application.routes.draw do
  devise_for :users

  resources :singers

  resources :conflicts

  resources :voice_parts

  root :to => 'voice_parts#index'

end

app/models/conflict.rb
class Conflict < ActiveRecord::Base
  belongs_to :singer
  attr_accessible :date, :end, :reason, :start, :type_of_conflict, :singer_id

  def singer_name
    singer.name if singer
  end
end

app/models/singer.rb
  class Singer < ActiveRecord::Base
  belongs_to :voice_part
  attr_accessible :name, :read, :voice_part_id

  validates :name, presence: true, uniqueness: true, :length => { :in => 2..50 },
            :format => { :with => /[a-zA-Z\s]/, :message => "Only letters allowed" }

  def voice_part_name
    voice_part.name if voice_part
  end

  scope :can_read, where("read = '1'")
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/voice_part.rb
class VoicePart < ActiveRecord::Base
  attr_accessible :max, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
end

app/controllers/conflicts_controller.rb
class ConflictsController < ApplicationController
  # GET /conflicts
  # GET /conflicts.json
  def index
    @conflicts = Conflict.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conflicts }
    end
  end

  # GET /conflicts/1
  # GET /conflicts/1.json
  def show
    @conflict = Conflict.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conflict }
    end
  end

  # GET /conflicts/new
  # GET /conflicts/new.json
  def new
    @conflict = Conflict.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conflict }
    end
  end

  # GET /conflicts/1/edit
  def edit
    @conflict = Conflict.find(params[:id])
  end

  # POST /conflicts
  # POST /conflicts.json
  def create
    @conflict = Conflict.new(params[:conflict])

    respond_to do |format|
      if @conflict.save
        format.html { redirect_to @conflict, notice: 'Conflict was successfully created.' }
        format.json { render json: @conflict, status: :created, location: @conflict }
      else
        format.html { render action: "new" }
        format.json { render json: @conflict.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conflicts/1
  # PUT /conflicts/1.json
  def update
    @conflict = Conflict.find(params[:id])

    respond_to do |format|
      if @conflict.update_attributes(params[:conflict])
        format.html { redirect_to @conflict, notice: 'Conflict was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conflict.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conflicts/1
  # DELETE /conflicts/1.json
  def destroy
    @conflict = Conflict.find(params[:id])
    @conflict.destroy

    respond_to do |format|
      format.html { redirect_to conflicts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/singers_controller.rb
class SingersController < ApplicationController
  # GET /singers
  # GET /singers.json
  def index
    @singers = Singer.can_read

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @singers }
    end
  end

  # GET /singers/1
  # GET /singers/1.json
  def show
    @singer = Singer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @singer }
    end
  end

  # GET /singers/new
  # GET /singers/new.json
  def new
    @singer = Singer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @singer }
    end
  end

  # GET /singers/1/edit
  def edit
    @singer = Singer.find(params[:id])
  end

  # POST /singers
  # POST /singers.json
  def create
    @singer = Singer.new(params[:singer])

    respond_to do |format|
      if @singer.save
        format.html { redirect_to @singer, notice: 'Singer was successfully created.' }
        format.json { render json: @singer, status: :created, location: @singer }
      else
        format.html { render action: "new" }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /singers/1
  # PUT /singers/1.json
  def update
    @singer = Singer.find(params[:id])

    respond_to do |format|
      if @singer.update_attributes(params[:singer])
        format.html { redirect_to @singer, notice: 'Singer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /singers/1
  # DELETE /singers/1.json
  def destroy
    @singer = Singer.find(params[:id])
    @singer.destroy

    respond_to do |format|
      format.html { redirect_to singers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/voice_parts_controller.rb
class VoicePartsController < ApplicationController
  # GET /voice_parts
  # GET /voice_parts.json
  def index
    @voice_parts = VoicePart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @voice_parts }
    end
  end

  # GET /voice_parts/1
  # GET /voice_parts/1.json
  def show
    @voice_part = VoicePart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @voice_part }
    end
  end

  # GET /voice_parts/new
  # GET /voice_parts/new.json
  def new
    @voice_part = VoicePart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @voice_part }
    end
  end

  # GET /voice_parts/1/edit
  def edit
    @voice_part = VoicePart.find(params[:id])
  end

  # POST /voice_parts
  # POST /voice_parts.json
  def create
    @voice_part = VoicePart.new(params[:voice_part])

    respond_to do |format|
      if @voice_part.save
        format.html { redirect_to @voice_part, notice: 'Voice part was successfully created.' }
        format.json { render json: @voice_part, status: :created, location: @voice_part }
      else
        format.html { render action: "new" }
        format.json { render json: @voice_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /voice_parts/1
  # PUT /voice_parts/1.json
  def update
    @voice_part = VoicePart.find(params[:id])

    respond_to do |format|
      if @voice_part.update_attributes(params[:voice_part])
        format.html { redirect_to @voice_part, notice: 'Voice part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @voice_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voice_parts/1
  # DELETE /voice_parts/1.json
  def destroy
    @voice_part = VoicePart.find(params[:id])
    @voice_part.destroy

    respond_to do |format|
      format.html { redirect_to voice_parts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conflicts_helper.rb
module ConflictsHelper
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/helpers/voice_parts_helper.rb
module VoicePartsHelper
end

app/views/conflicts/_form.html.erb
<%= form_for(@conflict, html: {class: "form-horizontal"}) do |f| %>
  <% if @conflict.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conflict.errors.count, "error") %> prohibited this conflict from being saved:</h2>

      <ul>
      <% @conflict.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="control-group">
  <%= f.label :date,
              class: 'control-label' %>
  <div class="controls">
    <%= f.date_select :date %>
  </div>
</div>
<div class="control-group">
  <%= f.label :start,
              class: 'control-label' %>
  <div class="controls">
    <%= f.time_select :start%>
  </div>
</div>
<div class="control-group">
  <%= f.label :end,
              class: 'control-label' %>
  <div class="controls">
    <%= f.time_select :end%>
  </div>
</div>
<div class="control-group">
  <%= f.label :reason,
              class: 'control-label' %>
  <div class="controls">
    <%= f.text_field :reason %>
  </div>
</div>
<div class="control-group">
  <%= f.label :type_of_conflict,
              class: 'control-label' %>
  <div class="controls">
    <div class="form-inline">
      <%= f.radio_button(:type_of_conflict, "PAC-Excused") %>
      <%= f.label(:type_of_conflict, "PAC-Excused") %>
    </div>
    <div class="form-inline">
      <%= f.radio_button(:type_of_conflict, "Excused") %>
      <%= f.label(:type_of_conflict, "Excused") %>
    </div>
    <div class="form-inline">
      <%= f.radio_button(:type_of_conflict, "Good Unexcused") %>
      <%= f.label(:type_of_conflict, "Good Unexcused") %>
    </div>
    <div class="form-inline">
      <%= f.radio_button(:type_of_conflict, "Bad Unexcused") %>
      <%= f.label(:type_of_conflict, "Bad Unexcused") %>
    </div>
  </div>
</div>

<div class="control-group">
    <span id="hideshow" class="btn btn-small">
        Hide help text
    </span>

    <div id="message">
        If you are not sure what category your conflict falls under, please select Bad Unexcused (BU).
    </div>
</div>

<div class="control-group">
  <%= f.label :singer, class: 'control-label' %>
  <div class="controls">
    <%= f.collection_select :singer_id, Singer.all, :id, :name %>
  </div>
</div>

<div class="form-actions" style="text-align: center">
  <%= f.submit class: "btn btn-large btn-primary" %>
</div>



<% end %>

app/views/conflicts/edit.html.erb
<h1>Editing Conflict</h1>

<%= render 'form' %>

<div class="text-center">
  <%= link_to 'Show', @conflict %> |
  <%= link_to 'Back', conflicts_path %>
</div>

app/views/conflicts/index.html.erb
<h1>Conflicts</h1>

<table class="span9 center-table">
  <tr>
    <th>Date</th>
    <th>Start</th>
    <th>End</th>
    <th>Reason</th>
    <th>Type of conflict</th>
    <th>Singer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conflicts.each do |conflict| %>
  <tr>
    <td><%= conflict.date.strftime("%d %b %y") %></td>
    <td><%= conflict.start.strftime("%I:%M%p") %></td>
    <td><%= conflict.end.strftime("%I:%M%p") %></td>
    <td><%= conflict.reason %></td>
    <td><%= conflict.type_of_conflict %></td>
    <td><%= conflict.singer_name %></td>
    <td><%= link_to 'Show', conflict %></td>
    <td><%= link_to 'Edit', edit_conflict_path(conflict) %></td>
    <td><%= link_to 'Destroy', conflict, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<div class="text-center">
  <%= link_to 'New Conflict', new_conflict_path %>
</div>

app/views/conflicts/new.html.erb
<h1>New Conflict</h1>

<%= render 'form' %>

<div class="text-center">
  <%= link_to 'Back', conflicts_path %>

</div>

app/views/conflicts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Conflict</h1>

<div class="text-center">
  <p>
    <b>Date:</b>
    <%= @conflict.date.strftime("%d %b %y") %>
  </p>

  <p>
    <b>Start:</b>
    <%= @conflict.start.strftime("%I:%M%p") %>
  </p>

  <p>
    <b>End:</b>
    <%= @conflict.end.strftime("%I:%M%p") %>
  </p>

  <p>
    <b>Reason:</b>
    <%= @conflict.reason %>
  </p>

  <p>
    <b>Type of conflict:</b>
    <%= @conflict.type_of_conflict %>
  </p>

  <p>
    <b>Singer:</b>
    <%= @conflict.singer_name %>
  </p>


  <%= link_to 'Edit', edit_conflict_path(@conflict) %> |
  <%= link_to 'Back', conflicts_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw5app</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="#">Choir Attendance</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "Voice Parts", :voice_parts %></li>
          <li><%= link_to "Singers", :singers %></li>
          <li><%= link_to "Conflicts", :conflicts %></li>
          <% if user_signed_in? %>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">

  <% if alert %>
      <div class="alert alert-error">
        <%= alert %>
      </div>
  <% end %>
  <% if notice %>
      <div class="alert alert-success">
        <%= notice %>
      </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/singers/_form.html.erb
<%= form_for(@singer, html: {class: "form-horizontal"}) do |f| %>
  <% if @singer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@singer.errors.count, "error") %> prohibited this singer from being saved:</h2>

      <ul>
      <% @singer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="offset2">
  <div class="control-group">
    <%= f.label :name,
                class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :read,
                class: 'control-label' %>
    <div class="controls">
      <div class="form-inline">
        <%= f.check_box(:read) %>
        <%= f.label(:read, "Can read music") %>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :voice_part, class: 'control-label' %>
    <div class="controls">
      <%= f.collection_select :voice_part_id, VoicePart.all, :id, :name %>
    </div>
  </div>

</div>

<div class="form-actions" style="text-align: center">
  <%= f.submit class: "btn btn-large btn-primary" %>
</div>

<% end %>

app/views/singers/edit.html.erb
<h1>Editing Singer</h1>

<%= render 'form' %>

<div class="text-center">
  <%= link_to 'Show', @singer %> |
  <%= link_to 'Back', singers_path %>
</div>

app/views/singers/index.html.erb
<h1>Singers (who can read music)</h1>

<table class="span5 center-table">
  <tr>
    <th>Name</th>
    <th>Read</th>
    <th>Voice Part</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @singers.each do |singer| %>
  <tr>
    <td><%= singer.name %></td>
    <td>
      <% if (singer.read == "1") %>
        <%= "Yes" %>
      <% else %>
        <%= "No" %>
      <% end %>
    </td>
    <td><%= singer.voice_part_name %></td>
    <td><%= link_to 'Show', singer %></td>
    <td><%= link_to 'Edit', edit_singer_path(singer) %></td>
    <td><%= link_to 'Destroy', singer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<div class="text-center">
  <%= link_to 'New Singer', new_singer_path %>
</div>

app/views/singers/new.html.erb
<h1>New Singer</h1>

<%= render 'form' %>
<div class="text-center">
  <%= link_to 'Back', singers_path %>
</div>

app/views/singers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
    <p>
      <b>Name:</b>
      <%= @singer.name %>
    </p>

    <p>
      <b>Can read music:</b>
      <% if (@singer.read == "1") %>
          <%= "Yes" %>
      <% else %>
          <%= "No" %>
      <% end %>
    </p>

    <p>
      <b>Voice part:</b>
      <%= @singer.voice_part_name %>
    </p>

  <%= link_to 'Edit', edit_singer_path(@singer) %> |
  <%= link_to 'Back', singers_path %>
</div>

app/views/voice_parts/_form.html.erb
<%= form_for(@voice_part, html: {class: "form-horizontal"}) do |f| %>
  <% if @voice_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voice_part.errors.count, "error") %> prohibited this voice_part from being saved:</h2>

      <ul>
      <% @voice_part.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="offset2">
  <div class="control-group">
    <%= f.label :name,
                class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :max,
                class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :max%>
    </div>
  </div>

</div>

<div class="form-actions" style="text-align: center">
  <%= f.submit class: "btn btn-large btn-primary" %>
</div>
<% end %>

app/views/voice_parts/edit.html.erb
<h1>Editing Voice Part</h1>

<%= render 'form' %>

<div class="text-center">
  <%= link_to 'Show', @voice_part %> |
  <%= link_to 'Back', voice_parts_path %>

</div>

app/views/voice_parts/index.html.erb
<h1>Voice Parts</h1>

<table class="span3 center-table">
  <tr>
    <th>Name</th>
    <th>Max</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @voice_parts.each do |voice_part| %>
  <tr>
    <td><%= voice_part.name %></td>
    <td><%= voice_part.max %></td>
    <td><%= link_to 'Show', voice_part %></td>
    <td><%= link_to 'Edit', edit_voice_part_path(voice_part) %></td>
    <td><%= link_to 'Destroy', voice_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<div class="text-center">
  <%= link_to 'New Voice Part', new_voice_part_path %>
</div>

app/views/voice_parts/new.html.erb
<h1>New Voice Part</h1>

<%= render 'form' %>

<div class="text-center">
  <%= link_to 'Back', voice_parts_path %>
</div>

app/views/voice_parts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Voice Part</h1>

<div class="text-center">
  <p>
    <b>Name:</b>
    <%= @voice_part.name %>
  </p>

  <p>
    <b>Max:</b>
    <%= @voice_part.max %>
  </p>


  <%= link_to 'Edit', edit_voice_part_path(@voice_part) %> |
  <%= link_to 'Back', voice_parts_path %>

</div>